# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Rao-6"
repo_name: "arxiv-papers-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Image Segmentation":
        filters: ["Image Segmentation", "Segmentation Network", "Instance Segmentation", 
                "Panoptic Segmentation", "Segmentation Transformer", "Medical Image Segmentation"]
    "Semantic Segmentation":
        filters: ["Semantic Segmentation", "Scene Parsing", "Pixel-wise Classification", "Mask Prediction", 
              "Semantic Parsing", "DeepLab", "SegFormer"]
    "Dense Prediction":
        filters: ["Dense Prediction", "Depth Estimation", "Optical Flow Estimation", 
                "Super Resolution", "Dense Correspondence", "Surface Normal Estimation"]
    "Efficient Models":
        filters: ["Lightweight Network", "Efficient Network", "Quantization", 
              "Knowledge Distillation", "Low-Resolution Segmentation", "Real-time Segmentation"]
